migration/multifd: Remove superfluous semicolons
checkpatch.pl report superfluous semicolons since commit
7cd156f7ce3, but this one was missed:

  scripts/checkpatch.pl f7f9f43aae7~..f7f9f43aae7
  ERROR: superfluous trailing semicolon
  #498: FILE: migration/multifd.c:308:
  +    ram_counters.transferred += transferred;;
  total: 1 errors, 1 warnings, 2073 lines checked

Fixes: f7f9f43aae7 ("multifd: Split multifd code into its own file")
Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
Reviewed-by: Li Qiang <liq3ea@gmail.com>
Message-Id: <20200921040231.437653-1-f4bug@amsat.org>
Signed-off-by: Laurent Vivier <laurent@vivier.eu>