error: Strip trailing '\n' from error string arguments (again)
Commit bbc479d, 6daf194d, be62a2eb and cad7116 got rid of a bunch, but
they keep coming back.  checkpatch.pl tries to flag them since commit
20484ac, but it's not very good at it.  Offenders tracked down with
Coccinelle script scripts/coccinelle/err-bad-newline.cocci, an updated
version of the script from commit cad7116.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Message-Id: <1470224274-31522-2-git-send-email-armbru@redhat.com>
Reviewed-by: Eric Blake <eblake@redhat.com>